version: '3.8'

services:
  app:
    build:
      context: ./app
    ports:
      - "5012:5012"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
      DATABASE_NAME: mydatabase
      ACCESS_PASSWORD: "1022"  # 접근 암호 환경 변수 추가
      PROTECTED_TABS: "device,report"  # 암호가 필요한 탭 ID 목록 [device,stick,qc,report,place]
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql
    command: --bind-address=0.0.0.0  # 모든 IP로 접근 허용


volumes:
  db_data:
