version: '3.8'

services:
  app:
    build:
      context: ./app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      ACCESS_PASSWORD: ${ACCESS_PASSWORD} # 접근 암호 환경 변수 추가
      PROTECTED_TABS: ${PROTECTED_TABS} # 암호가 필요한 탭 ID 목록
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "${DATABASE_EXTERNAL_PORT}:${DATABASE_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    command: --bind-address=0.0.0.0  # 모든 IP로 접근 허용

volumes:
  db_data: