version: '3.8'

services:
  app:
    build:
      context: ./app
    ports:
      - "5012:5012"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword
      - DATABASE_NAME=mydatabase
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD=rootpassword
      MYSQL_DATABASE=mydatabase
      MYSQL_USER=myuser
      MYSQL_PASSWORD=mypassword
    volumes:
      - db_data:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: